### ISSUE TITLE
Update of macOS installation instructions

### ISSUE THREAD

**Issue by raymondEhlers** [JETSCAPE/JETSCAPE#1]
This looks great so far, but I believe that the macOS installation instructions need an update. As described [here](https://github.com/Homebrew/homebrew-science/issues/6365), homebrew/science is unfortunately deprecated. Some formulas were migrated to the homebrew core (`root` and `hdf5` for example), but not all of them.

As an alternative, I think below is sufficient:

From homebrew/core:

```
cmake
doxygen
root
hdf5 --with-mpi # Note that this option changed
graphviz --with-app --with-bindings
graph-tool
​open-mpi
gsl​
```

And then from davidchall/homebrew-hep:

```
pythia
```

(although this pythia 8 seems to require hepmc2, so it's unclear that this will work given the hepmc3 dependency).

Also, from what I gathered from the presentation, it seemed that the minimal dependencies are `c++11,  cmake v3, zlib, Pythia8`, but the compilation currently fails on `hdf5`.

**Comment by raymondEhlers** [comment]
Hi @jhputschke,

Thanks for your rapid response. I looked at the installation requirements a bit more (I was trying to install everything standalone rather than using existing installations), it seems that there are also conflicting `hepmc` dependencies since `brew install pythia` depends on hepmc2, but JETSCAPE depends on `hepmc3`. It of course can be managed, but I imagine adding a formula for `hepmc3` in `davidchall/hep` and having `pythia` optionally depend on the particular `hepmc` version could make things much easier.

With regard to `hdf5`, it fails with:

```
[ 36%] Building CXX object src/CMakeFiles/JetScape.dir/initialstate/InitialFromFile.cc.o
In file included from /code/software/jetscape/src/src/initialstate/InitialFromFile.cc:16:
/code/software/jetscape/src/./src/initialstate/InitialFromFile.h:23:10: fatal error: 'hdf5.h' file not found
#include "hdf5.h"
         ^~~~~~~~
1 error generated.
```

Best,
Raymond

**Comment by jhputschke** [comment]
Hi Raymond,

Yes the Hepmc part is unfortunate with respect to pythia8 from brew, have to investigate how to avoid the conflict and update the instructions. Concerning hdf5, hmm, have to check the cmake includes.

Thanks for providing the information, they are super helpful!

Joern

**Comment by raymondEhlers** [comment]
Hi @jhputschke ,

Thanks for looking into it! Please let me know if you need anything else.

Best,
Raymond

**Comment by lgpang** [comment]
The following is what I got by updating homebrew to the newest version:
`brew update`

Indeed the homebrew/science/ formulae are removed and the pythia8 is renamed as pythia. The instructions will be updated soon for MacOS installation.

==> New Formulae
davidchall/hep/fastjet                             davidchall/hep/mcfm                                davidchall/hep/rivet                               davidchall/hep/vincia
davidchall/hep/fjcontrib                           davidchall/hep/openloops                           davidchall/hep/sherpa                              davidchall/hep/whizard
davidchall/hep/madgraph5_amcatnlo                  davidchall/hep/qcdnum                              davidchall/hep/thepeg                              davidchall/hep/yoda
==> Renamed Formulae
davidchall/hep/herwig++ -> davidchall/hep/herwig                                                      davidchall/hep/pythia8 ✔ -> davidchall/hep/pythia
==> Deleted Formulae
homebrew/science/a5                                homebrew/science/fasta                             homebrew/science/mcl                               homebrew/science/readseq
homebrew/science/abacas                            homebrew/science/fastml                            homebrew/science/med-file                          homebrew/science/readsim
homebrew/science/abinit                            homebrew/science/fastq-tools                       homebrew/science/megahit                           homebrew/science/reapr
homebrew/science/abyss-explorer                    homebrew/science/fasttree                          homebrew/science/megam                             homebrew/science/recon
homebrew/science/acado                             homebrew/science/fastuniq                          homebrew/science/meme                              homebrew/science/repeatmasker
homebrew/science/ace-corrector                     homebrew/science/fastx_toolkit                     homebrew/science/meraculous                        homebrew/science/repeatmodeler
homebrew/science/adam                              homebrew/science/fcgene                            homebrew/science/metaphlan                         homebrew/science/repeatscout
homebrew/science/adapterremoval                    homebrew/science/fermi                             homebrew/science/methpipe                          homebrew/science/rmblast
homebrew/science/adol-c                            homebrew/science/fermi-lite                        homebrew/science/metis4                            homebrew/science/rml-mmc
homebrew/science/afra                              homebrew/science/fermi2                            homebrew/science/mfem                              homebrew/science/rna-star
homebrew/science/alembic                           homebrew/science/fermikit                          homebrew/science/mfusg                             homebrew/science/rnammer
homebrew/science/alglib                            homebrew/science/fgsl                              homebrew/science/mhap                              homebrew/science/ropebwt
homebrew/science/alien-hunter                      homebrew/science/flash                             homebrew/science/minced                            homebrew/science/ropebwt2
homebrew/science/allpaths-lg                       homebrew/science/flexbar                           homebrew/science/minia                             homebrew/science/rstudio-server
homebrew/science/alpscore                          homebrew/science/flint                             homebrew/science/miniasm                           homebrew/science/sailfish
homebrew/science/amos                              homebrew/science/flux-simulator                    homebrew/science/minimap                           homebrew/science/sais
homebrew/science/analysis                          homebrew/science/fplll                             homebrew/science/mir-prefer                        homebrew/science/sally
homebrew/science/andi                              homebrew/science/fqzcomp                           homebrew/science/mira                              homebrew/science/salmon
homebrew/science/ann                               homebrew/science/freebayes                         homebrew/science/mitofy                            homebrew/science/salt
homebrew/science/anvio                             homebrew/science/freec                             homebrew/science/mlpack                            homebrew/science/sambamba
homebrew/science/apophenia                         homebrew/science/fsa                               homebrew/science/mlst                              homebrew/science/samblaster
homebrew/science/aragorn                           homebrew/science/fwdpp                             homebrew/science/moab                              homebrew/science/samtools@0.1
homebrew/science/arb                               homebrew/science/g2o                               homebrew/science/molden                            homebrew/science/sara
homebrew/science/arcs                              homebrew/science/gaemr                             homebrew/science/moose                             homebrew/science/sbagen
homebrew/science/aribas                            homebrew/science/galfit                            homebrew/science/mothur                            homebrew/science/scamp
homebrew/science/arow++                            homebrew/science/galib                             homebrew/science/mpsolve                           homebrew/science/scarpa
homebrew/science/arrayfire                         homebrew/science/galsim                            homebrew/science/mrbayes                           homebrew/science/scotch
homebrew/science/art                               homebrew/science/gap                               homebrew/science/mrfast                            homebrew/science/scotch5
homebrew/science/artemis                           homebrew/science/garli                             homebrew/science/msieve                            homebrew/science/scram
homebrew/science/ascii_plots                       homebrew/science/gatb                              homebrew/science/mtl                               homebrew/science/scrm
homebrew/science/astral                            homebrew/science/gatk                              homebrew/science/multi-worm-tracker                homebrew/science/sdsl-lite
homebrew/science/astrometry-net                    homebrew/science/geant4                            homebrew/science/mummer                            homebrew/science/seq-gen
homebrew/science/ate-pairing                       homebrew/science/geda-gaf                          homebrew/science/mumps                             homebrew/science/seqan
homebrew/science/atomic-pseudopotential-engine     homebrew/science/geneid                            homebrew/science/muscle                            homebrew/science/seqdb
homebrew/science/atompaw                           homebrew/science/genet                             homebrew/science/nanopolish                        homebrew/science/sequel
homebrew/science/atpdec                            homebrew/science/genewise                          homebrew/science/nauty                             homebrew/science/sextractor
homebrew/science/atram                             homebrew/science/getdp                             homebrew/science/ncbi-c++-toolkit                  homebrew/science/sfscode
homebrew/science/bact                              homebrew/science/gfan                              homebrew/science/nccmp                             homebrew/science/sga
homebrew/science/bali-phy                          homebrew/science/ggobi                             homebrew/science/ncl                               homebrew/science/shark
homebrew/science/bam-readcount                     homebrew/science/giira                             homebrew/science/nest                              homebrew/science/shrimp
homebrew/science/bamhash                           homebrew/science/gingr                             homebrew/science/neuron                            homebrew/science/sigrok-cli
homebrew/science/bamm                              homebrew/science/glimmer3                          homebrew/science/newick-utils                      homebrew/science/silo
homebrew/science/bamutil                           homebrew/science/glimmerhmm                        homebrew/science/newicktools                       homebrew/science/simpleitk
homebrew/science/barrnap                           homebrew/science/glpk448                           homebrew/science/nextflow                          homebrew/science/simulate-pcr
homebrew/science/bayestraits                       homebrew/science/gmap-gsnap                        homebrew/science/nexusformat                       homebrew/science/siril
homebrew/science/bbtools                           homebrew/science/gmcloser                          homebrew/science/nfft                              homebrew/science/sisl
homebrew/science/bcalm                             homebrew/science/gmtk                              homebrew/science/nglib                             homebrew/science/skewer
homebrew/science/beagle                            homebrew/science/gnuastro                          homebrew/science/niftilib                          homebrew/science/slepc
homebrew/science/beast2                            homebrew/science/gnudatalanguage                   homebrew/science/nip2                              homebrew/science/slicot
homebrew/science/beetl                             homebrew/science/grabix                            homebrew/science/nixio                             homebrew/science/sllib
homebrew/science/bfc                               homebrew/science/graphlan                          homebrew/science/nonpareil                         homebrew/science/smalt
homebrew/science/biobloomtools                     homebrew/science/gtsam                             homebrew/science/novoalign                         homebrew/science/smrtanalysis
homebrew/science/biocgal                           homebrew/science/gubbins                           homebrew/science/ntcard                            homebrew/science/snap
homebrew/science/biointerchange                    homebrew/science/h5utils                           homebrew/science/numdiff                           homebrew/science/snap-aligner
homebrew/science/biomake                           homebrew/science/harry                             homebrew/science/nusmv                             homebrew/science/snid
homebrew/science/biopieces                         homebrew/science/harvest-tools                     homebrew/science/nxtrim                            homebrew/science/snoscan
homebrew/science/biopp                             homebrew/science/hdf4                              homebrew/science/oases                             homebrew/science/snp-sites
homebrew/science/bitseq                            homebrew/science/healpix                           homebrew/science/oce                               homebrew/science/snpeff
homebrew/science/blasr                             homebrew/science/hisat                             homebrew/science/ococo                             homebrew/science/soapdenovo
homebrew/science/blat                              homebrew/science/hisat2                            homebrew/science/ogdraw                            homebrew/science/sollya
homebrew/science/blaze-lib                         homebrew/science/hlaminer                          homebrew/science/oma                               homebrew/science/soplex
homebrew/science/bless                             homebrew/science/hmmer2                            homebrew/science/omcompiler                        homebrew/science/sortmerna
homebrew/science/blis                              homebrew/science/hopdm                             homebrew/science/ome-common                        homebrew/science/spaced
homebrew/science/boost-compute                     homebrew/science/hotspot                           homebrew/science/ome-files                         homebrew/science/spatialite-gis
homebrew/science/bowtie                            homebrew/science/htsbox                            homebrew/science/ome-xml                           homebrew/science/spici
homebrew/science/bpel2owfn                         homebrew/science/humann2                           homebrew/science/openalpr                          homebrew/science/squeezambler
homebrew/science/bpipe                             homebrew/science/hyphy                             homebrew/science/openbr                            homebrew/science/ssake
homebrew/science/breseq                            homebrew/science/idba                              homebrew/science/opencollada                       homebrew/science/stacks
homebrew/science/busco                             homebrew/science/idcoefs                           homebrew/science/opencv ✔                          homebrew/science/statismo
homebrew/science/butterflow                        homebrew/science/igvtools                          homebrew/science/openfst                           homebrew/science/stiff
homebrew/science/bwtdisk                           homebrew/science/impute2                           homebrew/science/opengrm-ngram                     homebrew/science/stringtie
homebrew/science/calculix-ccx                      homebrew/science/infernal                          homebrew/science/opengrm-thrax                     homebrew/science/sumo
homebrew/science/cantera                           homebrew/science/insighttoolkit                    homebrew/science/openimageio                       homebrew/science/superlu43
homebrew/science/canu                              homebrew/science/inter-views                       homebrew/science/openmeeg                          homebrew/science/superlu_dist
homebrew/science/cap3                              homebrew/science/ipopt                             homebrew/science/openni                            homebrew/science/superlu_mt
homebrew/science/ccfits                            homebrew/science/iqtree                            homebrew/science/openni2                           homebrew/science/swarm
homebrew/science/cd-hit                            homebrew/science/itensor                           homebrew/science/orthofinder                       homebrew/science/swetest
homebrew/science/cddlib                            homebrew/science/itsol                             homebrew/science/osgearth                          homebrew/science/swrcfit
homebrew/science/cdo                               homebrew/science/iva                               homebrew/science/oswitch                           homebrew/science/symengine
homebrew/science/cdsclient                         homebrew/science/jblas                             homebrew/science/p4est                             homebrew/science/symphony
homebrew/science/cegma                             homebrew/science/jellyfish                         homebrew/science/paml                              homebrew/science/t-coffee
homebrew/science/celera-assembler                  homebrew/science/jellyfish-1.1                     homebrew/science/pandaseq                          homebrew/science/tabtk
homebrew/science/centrifuge                        homebrew/science/jmol                              homebrew/science/parallel-netcdf                   homebrew/science/tagdust
homebrew/science/cerulean                          homebrew/science/joinx                             homebrew/science/paraview                          homebrew/science/tamarin-prover
homebrew/science/cgns                              homebrew/science/jsbsim                            homebrew/science/parmetis                          homebrew/science/tasr
homebrew/science/circlator                         homebrew/science/k8                                homebrew/science/parsnp                            homebrew/science/tbl2asn
homebrew/science/circos                            homebrew/science/kaiju                             homebrew/science/pastix                            homebrew/science/tetgen
homebrew/science/ckon                              homebrew/science/kalign                            homebrew/science/pathd8                            homebrew/science/therion
homebrew/science/clark                             homebrew/science/kat                               homebrew/science/pathvisio                         homebrew/science/ticcutils
homebrew/science/clips                             homebrew/science/kent-tools                        homebrew/science/paxtools                          homebrew/science/timbl
homebrew/science/clonalframeml                     homebrew/science/kissplice                         homebrew/science/pbsuite                           homebrew/science/tisean
homebrew/science/clonehd                           homebrew/science/kmacs                             homebrew/science/pcap                              homebrew/science/tmv-cpp
homebrew/science/clustal-omega                     homebrew/science/kmc                               homebrew/science/pear                              homebrew/science/topcat
homebrew/science/clustal-w                         homebrew/science/kmergenie                         homebrew/science/perf                              homebrew/science/tophat
homebrew/science/cmdstan                           homebrew/science/kmerstream                        homebrew/science/phipack                           homebrew/science/trans-abyss
homebrew/science/cmor                              homebrew/science/kollector                         homebrew/science/phlawd                            homebrew/science/trans_proteomic_pipeline
homebrew/science/coinmp                            homebrew/science/kraken                            homebrew/science/phylip                            homebrew/science/transdecoder
homebrew/science/colpack                           homebrew/science/lapack-manpages                   homebrew/science/phyml                             homebrew/science/transpose
homebrew/science/concorde                          homebrew/science/last                              homebrew/science/phyutility                        homebrew/science/transrate-tools
homebrew/science/corset                            homebrew/science/lastz                             homebrew/science/phyx                              homebrew/science/transtermhp
homebrew/science/crfsuite                          homebrew/science/libbi                             homebrew/science/piler                             homebrew/science/trf
homebrew/science/crlibm                            homebrew/science/libbigwig                         homebrew/science/pilercr                           homebrew/science/triangle
homebrew/science/cryptoverif                       homebrew/science/libbuddy                          homebrew/science/pillow                            homebrew/science/trilinos
homebrew/science/cuba                              homebrew/science/libccd                            homebrew/science/pilon                             homebrew/science/trimadap
homebrew/science/cube                              homebrew/science/libcerf                           homebrew/science/plasma                            homebrew/science/trimal
homebrew/science/cufflinks                         homebrew/science/libctl                            homebrew/science/platypusvar                       homebrew/science/trimmomatic
homebrew/science/cusp                              homebrew/science/libdivsufsort                     homebrew/science/plink                             homebrew/science/trinity
homebrew/science/cutadapt                          homebrew/science/libeemd                           homebrew/science/plink2                            homebrew/science/trnascan
homebrew/science/cvblob                            homebrew/science/libfolia                          homebrew/science/plr                               homebrew/science/ucsc-genome-browser
homebrew/science/cytoscape                         homebrew/science/libgpkg                           homebrew/science/pnapi                             homebrew/science/ucto
homebrew/science/dadadodo                          homebrew/science/liblbfgs                          homebrew/science/poa                               homebrew/science/unafold
homebrew/science/daligner                          homebrew/science/libminc                           homebrew/science/pocl                              homebrew/science/uniqtag
homebrew/science/data-science-toolbox              homebrew/science/libpll                            homebrew/science/populations                       homebrew/science/uproc
homebrew/science/dazz_db                           homebrew/science/libsbml                           homebrew/science/poretools                         homebrew/science/utgb
homebrew/science/dealii                            homebrew/science/libsbol                           homebrew/science/prank                             homebrew/science/vague
homebrew/science/deeplearning4j-cli                homebrew/science/libsequence                       homebrew/science/primer3                           homebrew/science/varscan
homebrew/science/delly                             homebrew/science/libsigrokdecode                   homebrew/science/prokka                            homebrew/science/vcake
homebrew/science/des                               homebrew/science/lie                               homebrew/science/prooftree                         homebrew/science/vcfanno
homebrew/science/dextractor                        homebrew/science/lighter                           homebrew/science/proteinortho                      homebrew/science/vcflib
homebrew/science/dgtal                             homebrew/science/lightstringgraph                  homebrew/science/proverif                          homebrew/science/velvet
homebrew/science/dida                              homebrew/science/links-scaffolder                  homebrew/science/psmc                              homebrew/science/velvetoptimiser
homebrew/science/discovar                          homebrew/science/lis                               homebrew/science/pspp                              homebrew/science/viennarna
homebrew/science/discovardenovo                    homebrew/science/littler                           homebrew/science/pulseview                         homebrew/science/vigra
homebrew/science/dl_poly_classic                   homebrew/science/lmfit                             homebrew/science/pykep                             homebrew/science/vislcg3
homebrew/science/dotwrp                            homebrew/science/lmod                              homebrew/science/pymol                             homebrew/science/vsearch
homebrew/science/ds9                               homebrew/science/lobstr                            homebrew/science/qcl                               homebrew/science/vt
homebrew/science/dsdp                              homebrew/science/lola                              homebrew/science/qr_mumps                          homebrew/science/wcalc
homebrew/science/dsk                               homebrew/science/lp_solve                          homebrew/science/qsopt                             homebrew/science/wcslib
homebrew/science/dssp                              homebrew/science/lsd                               homebrew/science/qsopt_ex                          homebrew/science/wcstools
homebrew/science/dwgsim                            homebrew/science/lumpy-sv                          homebrew/science/quaff                             homebrew/science/weblogo
homebrew/science/dynare                            homebrew/science/m4ri                              homebrew/science/quake                             homebrew/science/wfdb
homebrew/science/e-mem                             homebrew/science/macse                             homebrew/science/qualimap                          homebrew/science/wiggletools
homebrew/science/ea-utils                          homebrew/science/mad-x                             homebrew/science/quast                             homebrew/science/wopr
homebrew/science/edena                             homebrew/science/madlib                            homebrew/science/quest                             homebrew/science/xbyak
homebrew/science/edirect                           homebrew/science/mafft                             homebrew/science/quicktree                         homebrew/science/xcdf
homebrew/science/einspline                         homebrew/science/maker                             homebrew/science/quip                              homebrew/science/xfig
homebrew/science/elemental                         homebrew/science/mallet                            homebrew/science/quorum                            homebrew/science/xmgredit
homebrew/science/elph                              homebrew/science/mantaflow                         homebrew/science/r8s                               homebrew/science/xmi-msim
homebrew/science/emboss                            homebrew/science/mapsembler2                       homebrew/science/racon                             homebrew/science/xraylib
homebrew/science/enblend-enfuse                    homebrew/science/maq                               homebrew/science/radx                              homebrew/science/xrmc
homebrew/science/ensembl-tools                     homebrew/science/mash                              homebrew/science/rainbow                           homebrew/science/xylib
homebrew/science/ess                               homebrew/science/masurca                           homebrew/science/rampart                           homebrew/science/yaggo
homebrew/science/etsf_io                           homebrew/science/mathgl                            homebrew/science/rapsearch2                        homebrew/science/yaha
homebrew/science/exabayes                          homebrew/science/mathomatic                        homebrew/science/rate4site                         homebrew/science/yass
homebrew/science/exonerate                         homebrew/science/matplotlib                        homebrew/science/raxml                             homebrew/science/yeppp
homebrew/science/express                           homebrew/science/maude                             homebrew/science/ray                               homebrew/science/yices
homebrew/science/fann                              homebrew/science/mbsystem                          homebrew/science/rcorrector                        homebrew/science/zoltan
==> Migrating pythia8 to pythia
==> Unlinking pythia8
==> Moving pythia8 children
==> Linking pythia

**Comment by lgpang** [comment]
The MacOS installation instructions have been updated to work with the new homebrew.

**Comment by raymondEhlers** [comment]
Hi @lgpang ,

Thanks for the updates! Once I installed `hdf5`, I was able to compile and run the brick test, so everything seems to be working well now!

Best,
Raymond

**Comment by dignity13** [comment]
I can install with "brew install" gsl, hepmc, fastjet, pythia; but I cannot install rivet and yoda. It says that  homebrew/science was deprecated. I also tried brew install davidchall/hep/<package-name> or homebrew/core/<package-name>.
