### ISSUE TITLE
Implementing HepMCFIFO Writer

### ISSUE THREAD

**Issue by hmehryar** [JETSCAPE/JETSCAPE#142]
- We already integrated the Jetscape to connect to Rivet for making its analysis
- For the sake of memory/storage consumption we need to return the output as a FIFO file
- Revit accepts the HEPMC File as input
- Therefore we need to Return a HEPMC FIFO output 

Requirement

- > implementing a simple FIFO Writer in the source
- > Implementing a simple HepMC output Piped as FIFO, and Check the result
- > adding XML configuration for HepMCFIFOWriter

**Comment by hmehryar** [comment]
implementing a sample hepmc fifo writer example

**Comment by hmehryar** [comment]
implmenting JetScapeWriterHepMCFifo Header and source

**Comment by amajumder** [comment]
Has this been merged into any public branch in JETSCAPE??
