### ISSUE TITLE
elastic scatterings in LBT?

### ISSUE THREAD

**Issue by wilkeqgp** [JETSCAPE/JETSCAPE#150]
I have a confusion at line 977+978 in LBT.cc:

`//                  Nscatter=KPoisson(Ncoll22);`
`      Nscatter=1; `

this is strange, since this will then always give an elastic scattering, whereas this seems to be the part of the code that is passed if there is an elastic or inelastic scattering (e.g. after `if(ran0(&NUM1)<probTot)`).

I think the proper code would be
 `	      if(ran0(&NUM1)<probCol/probTot) Nscatter=1 else Nscatter=0;` , 
or did I miss something?

**Comment by jhputschke** [comment]
Thanks for letting us know, we will clarify asap.

**Comment by LSchwiebert** [comment]
If this is the correct patch, I suggest using the following instead, which is more efficient:

Nscatter = ran0(&NUM1)<probCol/probTot;

This evaluates to 1 if true and 0 if false, so it gives the same result but avoids a branch instruction.

**Comment by shanshan-cao** [comment]
The original code should be correct. Even in the case of inelastic scattering, we still need to trigger an elastic scattering first, because the inelastic scattering is induced by elastic scattering in the physics we use. So as long as there is a scattering, we implement a 2->2 process first.

**Comment by wilkeqgp** [comment]
I see, thanks a lot! That makes sense I guess; I always thought that inelastic energy loss was more important, but I guess the option is that there are more elastic collisions (since every inelastic collision has an elastic collision), but that it still causes less energy loss. Do you maybe have a good reference where this is explained more completely?

**Comment by jhputschke** [comment]
Okay, hopefully Shanshan can provide the reference. With this I will close the issue.
Thanks
