### ISSUE TITLE
HepMC Integration Running JETSCAPE with SMASH

### ISSUE THREAD

**Issue by latessa** [JETSCAPE/JETSCAPE#162]
When running JETSCAPE with SMASH and requesting HepMC output from SMASH, SMASH reports that HepMC is not installed.

It has been confirmed that SMASH does produce HepMC output when used as a stand-alone application compiled and run in the JETSCAPE container.  Also, when compiling JETSCAPE with SMASH turned on, the compilation log shows that SMASH is finding and including the appropriate version of HepMC.   The issue therefore seems to be in the connection between JETSCAPE and SMASH.

**Comment by Hendrik1704** [comment]
In the COMP meeting, we decided not to follow up on this issue, which is not a bug issue from the JETSCAPE point of view.
When HepMC output with a proper particle decay history is requested, this should be built into the JETSCAPE writer and not rely on SMASH.
However, there is already a fix that will not be part of an official JETSCAPE release and can be found on the `latessa/smas_hepmc` branch.
