### ISSUE TITLE
LBT: GetHydroCellSignal call for t=z=0 

### ISSUE THREAD

**Issue by jhputschke** [JETSCAPE/JETSCAPE#165]
In line 975 in LBT.cc: GetHydroCellSignal(tLoc, xLoc, yLoc, zLoc, check_fluid_info_ptr);
Has situations in which tLoc and zLoc are 0 --> 
[Warning] Jetscape::FluidCellInfo Jetscape::EvolutionHistory::get_tz(Jetscape::real, Jetscape::real, Jetscape::real, Jetscape::real) const : the quest point is outside the light cone! t = 0, z = 0

**Comment by amajumder** [comment]
what is wrong with this?

**Comment by jhputschke** [comment]
Well, if nothing is wrong, why do we have a warning then?
