### ISSUE TITLE
Compile error in ThermPtnSampler.cc on Mac

### ISSUE THREAD

**Issue by jhputschke** [JETSCAPE/JETSCAPE#172]
When building on a Mac with clang only (no additional gcc installation) you will get this error since omp is not standard in clang on a Mac (Silicon and Intel) and even if installed separately via home-brew:
Building CXX object src/CMakeFiles/JetScape.dir/hadronization/ThermPtnSampler.cc.o
/Users/jputschke/JetScape/JETSCAPE/src/hadronization/ThermPtnSampler.cc:6:10: fatal error: 'omp.h' file not found
#include <omp.h>
I think Chun and myself found a solution for this and implemented it in the music cmake file, I assume it could be utilized here too.

Thanks

Joern

**Comment by LSchwiebert** [comment]
I didn't look at your proposed solution. I suggest using the following:

#ifdef _OPENMP
#include <omp.h>
#endif

_OPENMP should be defined by the compiler only if you are building with OpenMP enabled and the compiler supports OpenMP.

**Comment by jhputschke** [comment]
Thanks, yes, the fix was more referring towards how to change the CMakeFile.txt to include building with clang and openMP ...

**Comment by Hendrik1704** [comment]
This issue is solved by removing the inclusion of `omp.h` in the thermal parton sampler. This is merged into the RC branch for version 3.6.1, so I'll close this issue.
