### ISSUE TITLE
Reference to 'real' is ambiguous

### ISSUE THREAD

**Issue by kurtejung** [JETSCAPE/JETSCAPE#2]
During compilation on OSX 10.10, I ran into the following issue:

```
JETSCAPE/src/hydro/Brick.cc:87:26: error: reference to 'real' is ambiguous
void Brick::GetHydroInfo(real t, real x, real y, real z

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/complex:797:1: note: 
      candidate found by name lookup is 'std::__1::real'
real(const complex<_Tp>& __c)

.../JETSCAPE/./src/framework/RealType.h:24:15: note: candidate found by name lookup is
      'Jetscape::real'
typedef float real;
```
which looks like a conflict between a certain version of the gcc library and the jetscape namespaces.  The issue also propagates down to the GubserHydro and HydroFromFile objects.

We can try to explicitly declare all our namespace calls via ```using std::XXX``` instead of ```using namespace std``` but it might be a bit painful.

**Comment by jhputschke** [comment]
Hi Kurt,

Thanks for letting us know. I think indeed this is a version issue since for Mac OS X > 10.11 it does not seem to show up. We will investigate and try to clean up with better namespaces.

Joern

**Comment by jdmulligan** [comment]
Closing this, since we are only able to support the last ~2 operating systems, and there is no problem for macOS > 10.11
