### ISSUE TITLE
[Bug]: Discrepancy in the X and Y axes between the FreeStreaming and Hydro stages

### ISSUE THREAD

**Issue by ritobandatta** [JETSCAPE/JETSCAPE#236]
### Code Version

JETSCAPE 3.6.5

### Operating System

20.04.6 LTS (Focal Fossa)

### Container

Docker version 24.0.2

### Executable

runJetscape

### Bug Description

Transitioning from the free-streaming stage to the hydro stage while generating hydro on the fly results in a sudden change in the flow magnitude profile, as evident in the plot below. From the appearance, it seems the axes have been rotated by 90 degrees and then reflected vertically. The transition from free-streaming to hydro occurs at 1.6 fm.

Below is a comparison of the transition between a concurrent run and a saved run.
![Flow_Contour_XY_15](https://github.com/user-attachments/assets/ec899f4e-b901-49d0-a64f-4c0147171713)
![Flow_Contour_XY_16](https://github.com/user-attachments/assets/8b82f30f-69a5-44b2-9d88-3b5cf57c830d)
![Flow_Contour_XY_15](https://github.com/user-attachments/assets/51f06099-b3ac-4f8d-9336-eb792d860998)
![Flow_Contour_XY_16](https://github.com/user-attachments/assets/a854eb5a-01da-4dd9-819f-272ceee57a25)

### XML Input File

<?xml version="1.0"?>
<jetscape>
  <nEvents> 100 </nEvents>
  <setReuseHydro> true </setReuseHydro>
  <nReuseHydro> 500 </nReuseHydro>
  <JetScapeWriterAscii> on </JetScapeWriterAscii>
  <outputFilename>concurrentHydroMatterLBT800</outputFilename>
  <JetScapeWriterFinalStatePartonsAscii> on </JetScapeWriterFinalStatePartonsAscii>
  <vlevel> 0 </vlevel>
  <nEvents_printout> 50 </nEvents_printout>
  <Random>
    <seed>1</seed>
  </Random>
 
 
    <IS>
        <grid_max_x> 15 </grid_max_x>
        <grid_max_y> 15 </grid_max_y>
        <grid_max_z> 0 </grid_max_z>
        
        <grid_step_x> 0.2 </grid_step_x>
        <grid_step_y> 0.2 </grid_step_y>
        <Trento>
          <PhysicsInputs  projectile='Pb'
                  target='Pb'
                  sqrts='5020'
                  cross-section='7'
                  normalization='18.8'>
          </PhysicsInputs>
          <CutInputs
                centrality-low='0'
                centrality-high='5'>
          </CutInputs>
          <TransInputs  reduced-thickness='0.063'
                  fluctuation="1.05"
                  nucleon-width="1.12"
                  nucleon-min-dist="1.4">
          </TransInputs>
          <LongiInputs  mean-coeff="1.0"
                  std-coeff="3.0"
                  skew-coeff="0.0"
                  skew-type="1"
                  jacobian="0.8">
          </LongiInputs>
        </Trento>
    </IS>
  
  <Hard>
	<PGun></PGun>
  </Hard>
  
    <Preequilibrium>
        
        <tau0>0.0</tau0>
        <tauj>0.1</tauj>
        
        <taus>1.46</taus>
        <evolutionInMemory>1</evolutionInMemory>
        
        <FreestreamMilne>
            <name>FreestreamMilne</name>
        <freestream_input_file>freestream_input</freestream_input_file>
        </FreestreamMilne>
    </Preequilibrium>
 
  
  
  <Hydro>
    <AddLiquefier> false </AddLiquefier>
        <MUSIC>
            <beastMode>0</beastMode>
            <output_evolution_to_file>1</output_evolution_to_file>
            <output_evolution_to_memory>1</output_evolution_to_memory>
            <surface_in_memory>1</surface_in_memory>
            <Initial_time_tau_0>1.46</Initial_time_tau_0>
            <T_dependent_Shear_to_S_ratio>3</T_dependent_Shear_to_S_ratio>
            <eta_over_s_T_kink_in_GeV>0.223</eta_over_s_T_kink_in_GeV>
            <eta_over_s_low_T_slope_in_GeV>-0.776</eta_over_s_low_T_slope_in_GeV>
            <eta_over_s_high_T_slope_in_GeV>0.37</eta_over_s_high_T_slope_in_GeV>
            <eta_over_s_at_kink>0.096</eta_over_s_at_kink>
            <temperature_dependent_bulk_viscosity>3</temperature_dependent_bulk_viscosity>
            <zeta_over_s_max>0.133</zeta_over_s_max>
            <zeta_over_s_T_peak_in_GeV>0.12</zeta_over_s_T_peak_in_GeV>
            <zeta_over_s_width_in_GeV>0.072</zeta_over_s_width_in_GeV>
            <zeta_over_s_lambda_asymm>-0.122</zeta_over_s_lambda_asymm>
            <freezeout_temperature>0.136</freezeout_temperature>
        </MUSIC>
  </Hydro>
  
  <Eloss>
    <deltaT>0.1</deltaT>
    <formTime> -0.1</formTime>
    <maxT>9.0</maxT>
    <tStart> 0.6 </tStart> 
    <mutex>ON</mutex>
    <AddLiquefier> false </AddLiquefier>
    <Matter>
      <name>Matter</name>
      <matter_on> 1 </matter_on>
      <Q0> 2.0 </Q0>
      <T0> 0.16 </T0>
      <vir_factor> 0.25 </vir_factor>
      <in_vac> 0 </in_vac>
      <recoil_on> 1 </recoil_on>
      <broadening_on> 0 </broadening_on>
      <brick_med> 0 </brick_med>   
      <brick_length> 5.0 </brick_length>
      <hydro_Tc> 0.16 </hydro_Tc>
      
      
      
      
      
      
      
      
      
      <QhatParametrizationType> 5  </QhatParametrizationType>
      <qhat0> -2.0 </qhat0>  
      <alphas> 0.3 </alphas>
      <qhatA> 10.0 </qhatA>    
      <qhatB> 100.0 </qhatB>    
      <qhatC> 0.2 </qhatC>    
      <qhatD> 5.0 </qhatD>    
    </Matter>
    <Lbt>
      <name> Lbt </name>
      <Q0> 2.0 </Q0>
      <in_vac> 0 </in_vac>
      <only_leading> 0 </only_leading>
      <hydro_Tc> 0.16 </hydro_Tc>
      <alphas> 0.3 </alphas>
      <run_alphas>1</run_alphas>   
    </Lbt>
  </Eloss>
  
  
</jetscape>

**Comment by latessa** [comment]
PR #237 has been merged into the 3.6.6 RC, so I am closing this issue as completed.
