### ISSUE TITLE
old-ish linux(ubuntu) install instructions

### ISSUE THREAD

**Issue by rkunnawa** [JETSCAPE/JETSCAPE#3]
Hi All, 
Congrats on the release! 
I believe that the linux installations are a bit old. For one they begin with 
"1. Clone the repository from Github:
     - git clone https://github.com/amajumder/JETSCAPE-COMP.git"
which is already old. 

Then they go further with editing the framework modules 
"3. Change Cmake configuration for HepMC (If Cmake could not find HepMC)
     - Set "HEPMC_DIR" as the root directory of HepMC
     - Go to ../framework/Modules
     - Open FindHEPMC.cmake
          - vim FindHEPMC.cmake"
which is now located in JETSCAPE/cmakemodules. 
I installed all the external requirements in a location JETSCAPE/local/. I also pointed the LD_LIBRARY_PATH and PATH to the same loc. Do we still need to manually edit the corresponding cmake modules? 

Looking forward to getting it running! 

Cheers
Raghav

**Comment by rkunnawa** [comment]
Hi again, 
After fighting with boost for about an hour or so (apparently i had a couple of different versions of boost running in parallel in addition to multiple versions of hepmc :)), i got things running. The only point with the current linux readme is the locations and directories. otherwise, it all looks pretty good! 

very smooth running! 
[Info] 19MB  Run Event # = 199
[Info] 19MB  Run Hydro : Brick ...
[Info] 19MB  Run JetEnergyLoss ...
[Info] 19MB  JetScape finished after 200 events!
[Info] Finished!

CPU time: 5.711737 seconds.
Real time: 5.000000 seconds.

**Comment by mekhalaj** [comment]
Hi Raghav,
Thank you for getting involved and using JETSCAPE.
We will update the Linux installation instructions ASAP.
Usually we edit  cmake module files to give cmake some hints where to find packages and files. So if you install packages in default paths or the already included paths, you do not need to change cmake module files.
Happy to hear about smooth running.
