### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by kkauder** [JETSCAPE/JETSCAPE#34]
Just helped somebody with a fresh install and ran into multiple issues:
- boost needed to be installed. That's okay, but it should be added to the installation instructions. 
- Pythia8 was not installed. cmake should flag this as critical and refuse to finish configuring. Instead we caught it during make
- HDF5 is optional for many packages, but now one module requires it and isn't turned of properly in the cmake list. Again, this breaks the build instead of either turning off modules or eciting gracefully during cmake.
- The location of additional packages has changed to 
```sh
brew tap brewsci/science
```

- There are no (currently working) instructions on how to use graphviz and graph-fancy.py for our very nice graph output.

**Comment by jhputschke** [comment]
Thanks for catching the install issues. Good point concerning the graph visualization. Will add something in the readme and/or a commented up example with all the steps needed ..

**Comment by jdmulligan** [comment]
Fixed in new release JETSCAPE 3.0
(with exception of the graph visualization documentation -- @jhputschke please add as you like)
