### ISSUE TITLE
Choosing what parton/hadron information to save to disk?

### ISSUE THREAD

**Issue by TianyuDai** [JETSCAPE/JETSCAPE#36]
By the default setting of JETSCAPE, the whole parton showering will be saved to file, which can result in a huge output file. I understand that we can hack the code to make it print what we want. However, I am wondering if it would be better if JETSCAPE had options to allow the user to choose what they want to print (e.g. parton showering, final parton/hadron only).

**Comment by kkauder** [comment]
Hi Tianyu,

In order to keep file sizes manageable, I strongly suggest to use the "GZ" versions, which will make them smaller by much more than just reducing the shower information. 

For your request, it should be possible to solve it with very little code, like so:

template<class T>  
class MyWriter : public JetScapeWriterStream
{
void Write(weak_ptr<PartonShower> ps) override;
}

void MyWriter<T>::Write(weak_ptr<PartonShower> ps){
 // do nothing
}

I haven't tested this though.

**Comment by TianyuDai** [comment]
Hi Kolja (@kkauder), 
Thank you for your reply! Your first suggestion can save the disk space, but it still takes time to print. I found that by turning off the printing of parton showering and only printing final partons, the code runs much faster. 
I am currently solving the problem as your second suggestion: using my own writing function. However, I think it might be a good idea for JETSCAPE to have a default option as only printing final partons/hadrons, since many users of JETSCAPE only need final partons/hadrons to calculate observables.

**Comment by amajumder** [comment]
Hi Tianyu, 

There is a default option in JETSCAPE to write final state partons, and not the whole history. 
Please attach parton printer. What version of JETSCAPE are you using, 2 or 3. 
I can send you some simple code that allows you to do that, depending on the version used.

**Comment by TianyuDai** [comment]
Hi Abhijit (@amajumder ), 
I am currently using JETSCAPE2. A sample code would be very helpful. Thank you!

**Comment by amajumder** [comment]
Add the lines to the main program after you have added all the energy loss routines

    auto printer = make_shared<PartonPrinter> () ;
    jetscape->Add(printer);

Go to the folder /src/jet and take a look at the lines in partonprinter.cc 
dist_output << ipart << " " <<  pShower.get()->GetFinalPartons().at(ipart)->pid() << " " <<  pShower.get()->GetFinalPartons().at(ipart)->e() << " " <<  pShower.get()->GetFinalPartons().at(ipart)->px() << " " <<  pShower.get()->GetFinalPartons().at(ipart)->py() << " " <<  pShower.get()->GetFinalPartons().at(ipart)->pz() << endl;

You can change that to print out any other information in the parton class

**Comment by TianyuDai** [comment]
@amajumder Thank you very much for your help! This looks exactly what I need. If I want to use this function in JETSCAPE3.0, how should I modify the xml file or the main program?

**Comment by amajumder** [comment]
Add the line 
<PartonPrinter> <\PartonPrinter> after the <Eloss> section in both the master and user xml files.

**Comment by TianyuDai** [comment]
@amajumder 
I added `<PartonPrinter> <\PartonPrinter>` in both the master and user xml file, but it return the error information: 
`[Warning] void Jetscape::JetScapeXML::OpenXMLMasterFile() : XML Master file not found/not properly opened! Error code : 17`

**Comment by TianyuDai** [comment]
I am using public JETSCAPE 3.0.2

**Comment by amajumder** [comment]
Try using the private master. I am also pinging @jdmulligan  on this

**Comment by TianyuDai** [comment]
OK. Thank you!

**Comment by amajumder** [comment]
@bardelch why is this not resolved yet? You have the hadron printer now. This solves the problem that @TianyuDai had.

**Comment by bardelch** [comment]
This issue has a proposed solution in the branch particle-writer.  By adding 

`<HadronPrinter> </HadronPrinter>`

to the user XML.

**Comment by bardelch** [comment]
@TianyuDai let me know if the functionality works as you anticipate.
