### ISSUE TITLE
Small bug in MusicWrapper.cc

### ISSUE THREAD

**Issue by wilkeqgp** [JETSCAPE/JETSCAPE#37]
Dear contributers,

Thanks for the very nice code! While trying to run it I encountered  a problem that MUSIC ran smoothly, but nevertheless the temperature was always zero when reading it out. It turns out that line 57
  int flag_output_evo_to_file =
should read
  flag_output_evo_to_file =

That way the variable is not local anymore and MUSIC output gets properly processed.

Thanks again!

Wilke

**Comment by jdmulligan** [comment]
Hi Wilke,

Thanks for the report and the fix! We will have a look.

Best,
James

**Comment by jdmulligan** [comment]
Closing, with fix in new tag v3.0.1.
Thanks @wilkeqgp and @chunshen1987
