### ISSUE TITLE
Unable to compile JETSCAPE 2.2 with SMASH

### ISSUE THREAD

**Issue by j-f-paquet** [JETSCAPE/JETSCAPE#43]
Here's what I did:
1) Downloaded JETSCAPE and checked-out out Tag 2.2
2) I sourced this script:
```
export EIGEN_INSTALL_DIR=<my eigen install dir>
export EIGEN3_ROOT=<my eigen install dir>
export GSL=$(gsl-config --prefix)
export GSL_HOME=$(gsl-config --prefix)
export GSL_ROOT_DIR=$(gsl-config --prefix)
export JETSCAPE_DIR=`readlink -f .`

export SMASH_DIR=${JETSCAPE_DIR}/external_packages/smash/smash_code
export number_of_cores=`nproc --all`

export PYTHIAINSTALLDIR=<my PYTHIA dir>

export PYTHIA8DIR=${PYTHIAINSTALLDIR}/pythia8235
export PYTHIA8_ROOT_DIR=${PYTHIAINSTALLDIR}/pythia8235

export CC=gcc
export CXX=g++
export OpenMP_CXX=g++
```
3) `cd external_packages; bash get_music.sh ; bash get_freestream-milne.sh ; bash get_iSS.sh ; bash get_smash.sh`
4) `mkdir  build; cd build; cmake -Dmusic=ON -DiSS=ON -Dfreestream=ON -Dsmash=ON ..`
5) `make -j`

Everything works until the last step, the `make`, which stops on 
```
In file included from /scratch/tequila/public/external_packages/smash/smash_code/src/include/smash/experiment.h:38,
                 from /scratch/tequila/public/src/afterburner/SmashWrapper.h:23,
                 from /scratch/tequila/public/src/afterburner/SmashWrapper.cc:19:
/scratch/tequila/public/external_packages/smash/smash_code/src/include/smash/icoutput.h:20:10: fatal error: smash/config.h: No such file or directory
   20 | #include "smash/config.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/JetScape.dir/build.make:570: src/CMakeFiles/JetScape.dir/afterburner/SmashWrapper.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
Somehow, it seems that `smash/config.h` can't be found.

**Comment by doliinychenko** [comment]
Looking at it. Something must be wrong with the paths, likely in SMASH cmake. The file config.h is autogenerated from config.h.in, which looks like this:
```
/* the configured options and settings from cmake */
#define VERSION_MAJOR "@VERSION_MAJOR@"
#define CMAKE_SYSTEM "@CMAKE_SYSTEM@"
#define CMAKE_CXX_COMPILER_ID "@CMAKE_CXX_COMPILER_ID@"
#define CMAKE_CXX_COMPILER_VERSION "@CMAKE_CXX_COMPILER_VERSION@"
#define CMAKE_BUILD_TYPE "@CMAKE_BUILD_TYPE@"
#define BUILD_DATE "@BUILD_DATE@"
#define GIT_BRANCH "@GIT_BRANCH@"
```

This is done mainly to print the code version into the output files. Here is the cmake code that does the copying with substitution:
```
configure_file (
  "${CMAKE_CURRENT_SOURCE_DIR}/include/smash/config.h.in"
  "${CMAKE_CURRENT_BINARY_DIR}/include/smash/config.h"
)
```

Apparently either CMAKE_CURRENT_SOURCE_DIR or CMAKE_CURRENT_BINARY_DIR gets misinterpreted and either config.h.in is not found or config.h gets in the wrong place. In the latter case **a quick fix** is to find the config.h and copy it to the right place.

A long-term solution is of course is to fix the bug in SMASH cmake machinery. I'm working on that now. Cmake has several confusing variables like CMAKE_CURRENT_BINARY_DIR, CMAKE_PROJECT_DIR, CMAKE_CURRENT_SOURCE_DIR which look similar and may be identical until you include your project into some other project and they they are not identical any more and bugs show up.

**Comment by doliinychenko** [comment]
Here is the change to FindSMASH.cmake that should fix the problem properly:

```
--- a/cmake/FindSMASH.cmake
+++ b/cmake/FindSMASH.cmake
@@ -23,6 +23,7 @@ set(SMASH_INCLUDE_DIR
    $ENV{SMASH_DIR}/3rdparty/einhard
    $ENV{SMASH_DIR}/3rdparty/yaml-cpp-0.6.2/include
    $ENV{SMASH_DIR}/src/include
+   $ENV{SMASH_DIR}/build/src/include
    ${GSL_INCLUDE_DIR}
    ${Boost_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIR}
```

**Comment by j-f-paquet** [comment]
That worked, thanks Dima! I'll let you commit the fix. Thanks again
