### ISSUE TITLE
Segfault on missing Trento parameters in JETSCAPE v2.2 (and probably JSv3)

### ISSUE THREAD

**Issue by j-f-paquet** [JETSCAPE/JETSCAPE#46]
If Trento parameters are missing in the JETSCAPE parameter XML, the code segfaults.

For example, this is in the default JETSCAPE parameter XML 
``
                <LongiInputs    mean-coeff="1.0"
                                                std-coeff="3.0"
                                                skew-coeff="0.0"
                                                skew-type="1"
                                                jacobian="0.8">
                </LongiInputs>
``

If I take this out, the code segfaults.

Now, I don't know what behaviour we wish for the code when parameters are missing from the XML. I would assume something more graceful than a segfault, but "garbage in" -> "garbage out" isn't necessarily crazy either.

The other thing is that I assume we should be able to run JETSCAPE in 2+1D mode, in which case these parameters shouldn't be needed.

If we decide to resolve this only after we merge JETSCAPE-SIMS with master, we should think in advance about how we want to manage this. I believe this part of the code (Trento) is the same in JETSCAPE-SIMS as in the master.

**Comment by jdmulligan** [comment]
Hi @j-f-paquet 

Thanks for pointing out -- the XML functions actually have an optional second argument `isRequired` which default to true (i.e. will crash if element is not found), but if set to false will simply return a nullptr. So an easy fix could be to change TrentoInitial.cc to:

```
auto longi_opts = GetXMLElement({"IS", "Trento", "LongiInputs"}, false)
```

and then add logic to the remainder of the module to handle the 3D/2D case appropriately. I'm not  familiar with the details of the module or what is the status of 3D vs.  2D -- is this something SIMS can do?

**Comment by bardelch** [comment]
Currently the output from the missing parameters is: 

`[Warning] tinyxml2::XMLElement* Jetscape::JetScapeXML::GetElement(std::initializer_list<const char*>, bool) : XML element "IS:Trento:LongiInputs" not found, but is required. `

If there is a functional configuration where those parameters are not required we document examples where those examples make sense.

**Comment by bardelch** [comment]
So, this condition occurs when these parameters are missing from master and user XML.  When this happens the user has chosen to modify both.  Since this would happen immediately after modification and startup I would assume they would figure out to undo what they did without further prompting. 

Without further input, it seems to be working as designed.
