### ISSUE TITLE
twostagehydro example crashes while working on resonance decays 

### ISSUE THREAD

**Issue by rkunnawa** [JETSCAPE/JETSCAPE#49]
Hi All, 

I actually think that the twostagehydro example run via 
```
./runJetscape ../config/jetscape_user_twostagehydro.xml
```
is crashing in the second event while working on resonance decays. I ran for 10 events as the example suggests but the .out file is only written for 2 events.  In the first event actually there are a lot of warnings about 
```
Sampling finished in 0.0 seconds.

sample_using_dN_dxtdy_4all_particles finished in 0.2 seconds.
perform resonance decays... 
[Warning] void Jetscape::LiquefierBase::check_energy_momentum_conservation(const std::vector<Jetscape::Parton>&, std::vector<Jetscape::Parton>&) : A vertex does not conserve energy momentum!
[Warning] void Jetscape::LiquefierBase::check_energy_momentum_conservation(const std::vector<Jetscape::Parton>&, std::vector<Jetscape::Parton>&) : E = 0.000155248 GeV, px = 2.22045e-16 GeV, py = -8.88178e-16 GeV, pz = -2.77556e-17 GeV.
[Warning] void Jetscape::LiquefierBase::check_energy_momentum_conservation(const std::vector<Jetscape::Parton>&, std::vector<Jetscape::Parton>&) : A vertex does not conserve energy momentum!
[Warning] void Jetscape::LiquefierBase::check_energy_momentum_conservation(const std::vector<Jetscape::Parton>&, std::vector<Jetscape::Parton>&) : E = 0.000230833 GeV, px = 1.11022e-16 GeV, py = 4.44089e-16 GeV, pz = 2.22045e-16 GeV.
[Warning] Jetscape::FluidCellInfo Jetscape::EvolutionHistory::get_tz(Jetscape::real, Jetscape::real, Jetscape::real, Jetscape::real) const : the quest point is outside the light cone! t = 0, z = 0
...
```
and the code actually crashes with this output 
```
sample_using_dN_dxtdy_4all_particles finished in 0.2 seconds.
perform resonance decays... 
Error:particleSamples::perform_two_body_decay:can not found decays!
M = 0.8, m1 = 0.1, m2 = 0.8
```
the output music .dat files are also not usable (or maybe im not sure how to open/use them)?

**Comment by chunshen1987** [comment]
I think the error is caused because SMASH considers finite width spectral functions for hadronic resonance. Some decay channels are below the thresholds. 

You can turn off the particle decays in the xml file, which will avoid JETSCAPE to use the iSS to perform particle decays.

If you need to include feed down contributions, you need to add SMASH and use SMASH to perform decays.

**Comment by rkunnawa** [comment]
Thanks for the follow up @chunshen1987 Im a bit confused since i dont use smash here. is there something that i need to set or have in the parameter file that doesnt induce this error with iSS? I dont want to have hadronic transport, just run the existing decay chain for the jet + hydro? Is that doable or do i need to run with SMASH? thanks!

**Comment by chunshen1987** [comment]
You can set "afterburner_type" in the iSS_parameters.dat to 1 to avoid this error.

**Comment by rkunnawa** [comment]
That works nicely. thanks Chun!
