### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by kkauder** [JETSCAPE/JETSCAPE#5]
Forwarded from off-line communication:
1) probably should add that after using cmake that one should then make.

2) I ended up looking at the install.txt and installing HDF5....  Not sure if that was necessary or not.  

3) The jetscape_init.xml script lives in the example folder, which means that ./build/brickTest doesn't work out of the box.  I copied a version to the framework and then ran it again.

4) The data lives in build folder, so when running in the framework as stated one gets an error.  I made a folder and copied the version, so I had data_table/trento_auau200_cent.csv available to me.

Once I did that, it all seemed to run out of the box.

MY COMMENTS:
1) True. Looks like an older version of the README actually.

2) HDF5 is not needed by default, only when reading pregenerated hydro or running MUSIC.

3) The cmake script has a copy command in it to get it into your build directory. That's actually potentially an issue because every cmake will overwrite your custom cmake. But the other way
round is also unsatisfying.

4) That explains issue 3. The outdated README still assumes you run from outside the build directory. One should run in the build directory, and the csv will be there too.

**Comment by kkauder** [comment]
I'm updating the README.

**Comment by jdmulligan** [comment]
Fixed in new release JETSCAPE 3.0
