### ISSUE TITLE
Bug in SMASH wrapper in case of >1 hydro event

### ISSUE THREAD

**Issue by doliinychenko** [JETSCAPE/JETSCAPE#55]
A school participant complained me about JetScape + SMASH simulation crash with the following config
[jetscape_smash.xml.txt](https://github.com/JETSCAPE/JETSCAPE/files/5067795/jetscape_smash.xml.txt). It turns out that I misunderstood the way, how hydro passes particles to sampler and smash, which caused this bug. 

For each hydro event there can be N sampler events. Particles from all N sampler events are saved in a structure, which SMASH wrapper passes to SMASH. Next hydro event executes new N sampler events and resets this structure, so particles from previous hydro event are forgotten. SMASH wrapper didn't know that and incremented the event number further instead of resetting it to 0 for each new hydro event. That number was used as an array index, so for the second hydro event it segfaulted.

Attached is a patch to fix the bug.
[fix_smash_wrapper_bug.patch.txt](https://github.com/JETSCAPE/JETSCAPE/files/5067811/fix_smash_wrapper_bug.patch.txt)

**Comment by doliinychenko** [comment]
Hmm, can't add myself as an assignee. Could someone who has rights assign me, apply the patch, check that there is no more crash with the attached config, review the changes, and merge the code to master?

**Comment by jdmulligan** [comment]
Hi Dima, Thanks, can you please open a pull request with the proposed changes?

**Comment by doliinychenko** [comment]
Done. Please review.

**Comment by doliinychenko** [comment]
Why is it open? It was merged long ago...
