### ISSUE TITLE
HepMC output has wrong status codes

### ISSUE THREAD

**Issue by cnattras** [JETSCAPE/JETSCAPE#58]
HepMC output should have status codes following the standards here
https://arxiv.org/pdf/1912.08005.pdf
in Appendix A.  An "undecayed physical particle" (pi+/-) should have a status code 1 and "decayed physical particles" (K0S, pi0, etc) should have status code 2.  There are uses for other status codes, but they would be invisible to, say, Rivet.  Right now, when you run over a JETSCAPE HepMC file, you get no particles in the event. There is virtually always a projection to "Final State" particles or (for instance) "ALICE Physical Primary".  These look for a status code of 1 or 2.  Rivet assumes that the HepMC produced follows the required standards.

**Comment by bardelch** [comment]
The corrected status codes have been merged.  Please check for consistency as needed.
