### ISSUE TITLE
open jupyter notebook

### ISSUE THREAD

**Issue by gauri20-eng** [JETSCAPE/JETSCAPE#73]
when I run this command- jupyter-notebook --ip 0.0.0.0 --no-browser. After than found
link- To access the notebook, open this file in a browser:
        file:///home/jetscape-user/.local/share/jupyter/runtime/nbserver-12-open.html
    Or copy and paste one of these URLs:
        http://f6085ad536bf:8888/?token=e39ddace119a67daefc154cd3823b7a0a0383d478e93ca48
     or http://127.0.0.1:8888/?token=e39ddace119a67daefc154cd3823b7a0a0383d478e93ca48
But always open this link so creat error in loading.How to open these files ? and have any other process for open these files?

**Comment by amajumder** [comment]
I dont think this has anything to do with the JETSCAPE code base. For questions on the Jupyter notebook go to the JETSCAPE summer school slack space and ask your question.
