### ISSUE TITLE
allocation of cores

### ISSUE THREAD

**Issue by aswin1447** [JETSCAPE/JETSCAPE#82]
On calling the runJetscape script, all the cores of the system are allocated for Jetscape. How to stop that and allocate only a certain number of cores?

**Comment by jdmulligan** [comment]
Hi @aswin1447,

JETSCAPE itself will not allocate all cores of the system (it is not multi-core), however you are presumably running MUSIC? The MUSIC module will by default allocate all cores. You can limit the number of cores as shown here: https://github.com/JETSCAPE/JETSCAPE/tree/master/external_packages#music-support

(@chunshen1987 please correct/add anything else I miss)
