### ISSUE TITLE
Run_jetscape_code_error

### ISSUE THREAD

**Issue by gauri20-eng** [JETSCAPE/JETSCAPE#83]
We are trying to reproduce some results (such as pseudorapidity distribution of charged hadrons, p_T distribution, etc.) in Au+Au collisions at 200 GeV center-of-mass energy using JETSCAPE.

In "jetscape_user.xml" file we have used -
1> TRENTO for initial conditions
2> PythiaGun for hard process with pTHatMin=50, pTHatMax=70 (we are still trying to figure out the range of pTHat. Is it centrality dependent? How to find pTHat value for different collision systems and colliding energies?)
3> FreestreamMilne for pre-equilibrium
4> MUSIC for Hydro module
5> iSS for soft hadronization
6> SMASH for hadronic afterburner

While running the JETSCAPE for 100 events, we get some warnings in each event such as-
1> ⚠ Can not create folder ./outputs ...
2> ⚠ not all chosen particles are in the pdg particle list!
     ⚠ There are 133 particles can not be found in the pdg particle list!
     ⚠ Their monte carlo numbers are:
    ⚠ 9060225
    ⚠ -9010213
    ⚠ -9962112 ...
3> [Warning] bool Jetscape::Hadron::CheckOrForceHadron(int, double) : id =     -2116 is not recognized as a hadron! Add it as a new type of particle.
[Warning] bool Jetscape::Hadron::CheckOrForceHadron(int, double) : id = -2216 is not recognized as a hadron! Add it as a new type of particle.
[Warning] bool Jetscape::Hadron::CheckOrForceHadron(int, double) : id = -1216 is not recognized as a hadron! Add it as a new type of particle.

Finally, after JETSCAPE finished for 100 events we have "test_out1.dat" as an output file in ASCII format.
After that when we run ./FinalStateHadrons or ./FinalSatePartons we get a message: Aborted (core dumped). We have attached the screenshot of the error message in "jetscape.png" file. Also, we have attached the "jetscape_user.xml" file.

Kindly, provide your feedback and suggestions so that we can resolve the issues regarding the warnings that we are getting while running JETSCAPE and the error while running ./FinalStateHadrons.
Also, please comment on the selection of pTHat range in PythiaGun.
[jetscape_user.pdf](https://github.com/JETSCAPE/JETSCAPE/files/6101340/jetscape_user.pdf)
![jetscape](https://user-images.githubusercontent.com/68547580/110322248-d9785d00-8038-11eb-9513-fb96a636cc8e.png)

**Comment by jdmulligan** [comment]
Hi @gauri20-eng, 
It looks like your jetscape_user.xml has multiple types of certain modules when you should choose only one (Hard, Preequilibrium, Hydro). Take a closer look at what modules you actually want to run, and update your configuration file accordingly. I would also suggest for the sake of getting familiar with the framework to start with a simple configuration (e.g. the PP19 xml file provided by us), and add in additional modules one-by-one.
