### ISSUE TITLE
Event initialization change in SMASH-2.0

### ISSUE THREAD

**Issue by stdnmr** [JETSCAPE/JETSCAPE#85]
The `initialize_new_event()` function changed for `SMASH-2.0` with [this commit](https://github.com/smash-transport/smash-devel/commit/2fb3496e51480acba1c568cdb318b3e1a7257e14) causing a problem for the `SmashWrapper`. I saw that you fixed the version recently to `SMASH-1.8.1`, which prevents it for now.

But, should you decide to upgrade in the future, this simple patch should resolve the issue:

```diff
diff --git a/src/afterburner/SmashWrapper.cc b/src/afterburner/SmashWrapper.cc
index 223ec8a..fbf5130 100644
--- a/src/afterburner/SmashWrapper.cc
+++ b/src/afterburner/SmashWrapper.cc
@@ -121,7 +121,7 @@ void SmashWrapper::ExecuteTask() {
   for (unsigned int i = 0; i < n_events; i++) {
     JSINFO << "Event " << i << " SMASH starts with "
            << modus->jetscape_hadrons_[i].size() << " particles.";
-    smash_experiment_->initialize_new_event();
+    smash_experiment_->initialize_new_event(i);
     if (!only_final_decays_) {
       smash_experiment_->run_time_evolution();
     }
```

I leave this comment here as an issue, feel free to store for when applicable and close issue afterwards.

**Comment by jdmulligan** [comment]
Thanks @stdnmr -- we add this to #102 and will deploy in the next release
