### ISSUE TITLE
jetscape analyze

### ISSUE THREAD

**Issue by gauri20-eng** [JETSCAPE/JETSCAPE#86]
How to set pT hat bin in example.yaml file for p-p and Pb-Pb collision?  I had set pT hat bin from given PP19.yaml file so create different pTbin directory.
So, how to set only one pT hat bin for p-p and Pb-Pb collision and why set this?

**Comment by jdmulligan** [comment]
Hi @gauri20-eng, I am not sure if I completely understand your question, but you can set the pt hat bin directory in your "user" XML file, such as PP19.yaml. You can take a look at the "master" XML file to find the syntax for any options you be interested in.
